### ISSUE TITLE
No supply drops in Town.

### ISSUE THREAD

**Issue by bjincy** [GMDevinity/BattleRoyaleIssues#165]
I have seen on several occasions, the supply drop get stuck on non-climbable roofs where players cant get to.  I feel they should instead drop closer to pier or in the field by that area.

**Comment by Donkie** [comment]
the supply drops are dropped by the plane and fly a random direction once its dropped, I can't really control where it lands specifically. Either I can make it drop more towards the center of the map, or we'll have to deal with it sometimes landing on the roof. (I see the crate landing on the roof as something that could be fun and annoying rather than a bug)

**Comment by bjincy** [comment]
fair point, I guess it makes sense as far as reality
