### ISSUE TITLE
Scale "pre-zone" time to number of players in server.

### ISSUE THREAD

**Issue by AOBatch** [GMDevinity/BattleRoyaleIssues#64]
Scale the time before the zone even appears to the number of players in the server. If you have less players then make the zone appear much more quickly.

This should make rounds with fewer players much more fun as you're not waiting around as long (Both dead & alive)

**Comment by CounterCraftz** [comment]
In addition, I think the circle should be scaled as well based on the # of players alive before it spawns
 
Less players = less sphere radius
![image](http://f.devinity.org/x9kEDK)
this is just an example, not sure if some type of equation can be made to calculate # of players alive to sphere radius

**Comment by CcLLL** [comment]
I like this idea way better, i dont think it would necessarily prolong the rounds but instead make the experience better, imo.

**Comment by Donkie** [comment]
Currently the sphere spawns after 120 seconds, and it spawns as 7000 units radius

**Comment by Donkie** [comment]
I'm not sure about decreasing the sphere size because once it starts shrinking it'll go pretty rapidly then. I think we should start with trying out delay before it spawns to begin with.

What about:
`sphereDelay = clamp( 3 * playerCount + 30, 60, 120 )`
and then rounding it to nearest 5 seconds
will yield:
![](http://f.donkie.co/bU1BA)
