### ISSUE TITLE
Bundle of random ideas

### ISSUE THREAD

**Issue by CcLLL** [GMDevinity/BattleRoyaleIssues#78]
(1)Airdrop, which could contain the m82,m24 and stronger weapons. Could add some more weapons that you will only find in the airdrop

(2)Dmg indicator, so you have some idea how much hp your target have left

(3)Team indicator. There would be a small start/teamname or whatever over your teammates head. Which would allow you to see where your current team members are much more easily, and position calling would also become much more viable.
 
(4) Perks. you have some perks available at certain lvls. You can only equip 3 perks at any given time. Could be something like, 10% faster reload rate. 20% more ammo pickup with all smg. More resistence against explosive something like that. If you guys like this idea i could go more into details of what i have in mid.

**Comment by ghost** [comment]
Counter linked what looks like a good damage indicator - http://steamcommunity.com/sharedfiles/filedetails/?id=1214185893

For the team indicator, what if you could just see your teammates outline through everything in the world?  So you could CLEARLY tell who your teammates are and always see where they are, kinda like how it is in R6: Siege.  Image for reference: https://i.ytimg.com/vi/jdkHarWeJvU/maxresdefault.jpg

I dunno about the perks doe, so players who are good will be better because they will easily be a high level to get perks and it will give an advantage over newer players, yes a small one but still an advantage, I don't know about this one.

**Comment by CcLLL** [comment]
Yer the outline thing is where i was trying to get at.

but about the perks i'm not saying it should be any op perks at all. Just something to grind for and it's not like new players wouldn't have a chance since you would get perks at everything 10lvl. And the first 20lvls you can get pretty quick.

**Comment by CounterCraftz** [comment]
For team indicators, I think they should appear only at close proximity. They build up lag and I'm not sure if you would see their outline from the edge of the map. Maybe like within circle range or 3/4th of it would be good. You also have the minimap which also helps.

For the perks, I'm not so sure either because on the conference, I've heard a couple of mentions that it should be purely based on cosmetics.

**Comment by CounterCraftz** [comment]
I really like the airdrop idea. But instead of making it fall linearly and on one exact position like NA which is pretty boring, it should be multiple positions and maybe attach a parachute on the cargo and make it fall freely around the designated position. Just like PUBG or whatever

**Comment by Donkie** [comment]
Team indicators, should they be visible through walls?
Visible:
![](http://f.donkie.co/apaCk)

Not visible:
![](http://f.donkie.co/x1Jw7)
